permalink: /:year/:month/:day/:title 

exclude: [".rvmrc", ".rbenv-version", "README.md", "Rakefile", "changelog.md"]
auto: true
pygments: true

title : Zakai
author :
  name : Zakai Zhao
  email : ZakaiZhao@gmail.com
  github : Zakai
  twitter : username
  feedburner : zakai

production_url : http://zakai.github.com

JB :
  version : 0.2.13
  archive_path: /archive.html
  categories_path : /categories.html
  tags_path : /tags.html
  comments :
    provider : disqus
    disqus :
      short_name : jekyllbootstrap
    livefyre :
      site_id : 123
    intensedebate :
      account : 123abc
    facebook :
      appid : 123
      num_posts: 5
      width: 580
      colorscheme: light

  sharing :
    provider : false